# Generated by Django 4.1 on 2022-09-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_img_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(upload_to='saved pictures'),
        ),
    ]
