# Generated by Django 4.1 on 2022-09-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='decs',
            new_name='desc',
        ),
    ]
